export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_SAMSUNG_PRODUCT_REQUEST = "GET_SAMSUNG_PRODUCT_REQUEST";
export const GET_SAMSUNG_PRODUCT_SUCCESS = "GET_SAMSUNG_PRODUCT_SUCCESS";
export const GET_SAMSUNG_PRODUCT_FAIL = "GET_SAMSUNG_PRODUCT_FAIL";

export const GET_HUAWEI_PRODUCT_REQUEST = "GET_HUAWEI_PRODUCT_REQUEST";
export const GET_HUAWEI_PRODUCT_SUCCESS = "GET_HUAWEI_PRODUCT_SUCCESS";
export const GET_HUAWEI_PRODUCT_FAIL = "GET_HUAWEI_PRODUCT_FAIL";

export const GET_IPHONE_PRODUCT_REQUEST = "GET_IPHONE_PRODUCT_REQUEST";
export const GET_IPHONE_PRODUCT_SUCCESS = "GET_IPHONE_PRODUCT_SUCCESS";
export const GET_IPHONE_PRODUCT_FAIL = "GET_IPHONE_PRODUCT_FAIL";

export const GET_OTHERS_PRODUCT_REQUEST = "GET_OTHERS_PRODUCT_REQUEST";
export const GET_OTHERS_PRODUCT_SUCCESS = "GET_OTHERS_PRODUCT_SUCCESS";
export const GET_OTHERS_PRODUCT_FAIL = "GET_OTHERS_PRODUCT_FAIL";
